#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Mon Feb  2 17:14:45 2015

from gui.App import TinyhebApp

if __name__ == "__main__":
    tinyheb = TinyhebApp(0)
    tinyheb.MainLoop()
